version: '3.5'
services:
  web:
    image: febryandana/odoo:16
    build:
      context: ./odoo
      dockerfile: Dockerfile
    container_name: odoo16
    environment:
      - HOST=postgres
      - PORT="5432"
      - USER=root
      - PASS=gladiators88
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:15.1-bullseye
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=odoodb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=gladiators88
