---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: odoo
  labels:
    app: postgres
data:
  POSTGRES_DB: odoodb
  POSTGRES_USER: root
  POSTGRES_PASSWORD: gladiators88
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/volume/postgresql-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-claim
  namespace: odoo
spec:
  volumeName: postgresql-data
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.1-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
    volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgresql-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: odoo
  labels:
    app: postgres
spec:
  # clusterIP: 10.233.70.51
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 35432
  selector:
    app: postgres
