---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo
  labels:
    app: odoo
data:
  HOST: postgres
  PORT: "5432"
  USER: root
  PASSWORD: gladiators88
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          image: febryandana/odoo:16
          imagePullPolicy: Always
          ports:
            - containerPort: 8069
          envFrom:
            - configMapRef:
                name: odoo-config
---
apiVersion: v1
kind: Service
metadata:    
  name: odoo
  namespace: odoo
spec:
  # clusterIP: 10.233.70.52
  type: NodePort
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 38069
