name: CI/CD Odoo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Odoo image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./odoo
          tags: |
            febryandana/odoo:16
            febryandana/odoo:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # - name: Build Postgresql image and push to Docker Hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./odoo
      #     tags: |
      #       febryandana/postgresql:15.1
      #       febryandana/postgresql:latest
      #     push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  trivy:
    name: Scan image vulnerability
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Scan Odoo image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'febryandana/odoo:16'
          format: 'table'
          exit-code: '0'
          severity: 'MEDIUM,HIGH,CRITICAL'
          
      # - name: Run Trivy vulnerability scanner for Postgresql
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: 'febryandana/postgresql:15.1'
      #     format: 'table'
      #     exit-code: '0'
      #     severity: 'MEDIUM,HIGH,CRITICAL'